from Syntax.lexicon import Lexicon
from sen_generator import SentenceGenerator
from Database.DB import db
import random

# def generate_all_sentences():
#     """Generate all sentence types without sampling."""
#     lex = Lexicon()
#     generator = SentenceGenerator(lex)

#     print("Generating atomic sentences...")
#     generator.generate_atomic_sentences()

#     print("Generating simple quantified sentences...")
#     generator.generate_simple_quantified_sentences()

#     print("Generating multiply quantified sentences...")
#     generator.generate_multiply_quantified_sentences()

#     print("Generating reciprocal quantified sentences...")
#     generator.generate_reciprocal_quantified_sentences()

#     print("Generating complex dyadic sentences...")
#     generator.generate_complex_dyadic_sentences()

#     print("Generating compound sentences...")
#     generator.generate_conjunctions()
#     generator.generate_disjunctions()
#     generator.generate_conditionals()
#     generator.generate_biconditionals()
#     generator.generate_nested_conditionals()


# def create_samples(n=5):
#     """Create a markdown file with samples of each sentence type."""
#     with open("sentence_samples.md", "w") as f:
#         f.write("# ArgBench Sentence Samples\n\n")
#         f.write("This file contains samples of all sentence types generated by the ArgBench sentence generator.\n\n")

#         def write_section(sentence_type, subtype=None):
#             kwargs = {"type": sentence_type}
#             if subtype:
#                 kwargs["subtype"] = subtype
#             sentences = db.get_sentence_where(**kwargs)
#             samples = random.sample(sentences, min(n, len(sentences)))

#             # Write section header
#             header = f"### {sentence_type}_{subtype}"
#             f.write(f"{header}\n\n")

#             # Write samples
#             for s in samples:
#                 f.write(f"- {s['sentence']} :: `{s['form']}`\n")
#             f.write("\n")

#         # Atomic sentences
#         f.write("## Atomic Sentences\n\n")
#         write_section("atomic", "monadic")
#         write_section("atomic", "dyadic")

#         # Quantified sentences
#         f.write("## Quantified Sentences\n\n")
#         write_section("quantified", "universal_affirmative")
#         write_section("quantified", "particular_affirmative")
#         write_section("quantified", "universal_negative")
#         write_section("quantified", "particular_negative")
#         write_section("quantified", "only_restrictor")
#         write_section("quantified", "all_all")
#         write_section("quantified", "all_some")
#         write_section("quantified", "some_all")
#         write_section("quantified", "some_some")
#         write_section("quantified", "no_all")
#         write_section("quantified", "no_some")
#         write_section("quantified", "rev_some_all")
#         write_section("quantified", "rev_no_all")
#         write_section("quantified", "some_self")
#         write_section("quantified", "all_all_back")
#         write_section("quantified", "some_all_back")
#         write_section("quantified", "some_some_back")
#         write_section("quantified", "all_some_back")
#         write_section("quantified", "no_some_back")
#         write_section("quantified", "all_all_all")
#         write_section("quantified", "some_some_some")

#         # Compound sentences
#         f.write("## Connective Sentences\n\n")
#         write_section("conjunction", "simple")
#         write_section("conjunction", "vp_ellipsis")
#         write_section("conjunction", "contrastive")
#         write_section("disjunction", "simple")
#         write_section("disjunction", "vp_ellipsis")
#         write_section("disjunction", "unless")
#         write_section("disjunction", "negated_disjunct")
#         write_section("conditional", "if_then")
#         write_section("conditional", "only_if")
#         write_section("conditional", "nested")
#         write_section("biconditional", "if_and_only_if")
#         write_section("biconditional", "just_in_case")


# def generate():
#     """Generate all sentences and create a markdown file with samples."""
#     # First generate all sentences
#     generate_all_sentences()

#     # Then create the markdown file with samples
#     print("\nCreating samples markdown file...")


if __name__ == "__main__":
    lex = Lexicon()
    generator = SentenceGenerator(lex)

    # generator.generate_conjunctions(sentence_types=[{"type": "quantified", "subtype": "name_all"}])
    # generator.generate_disjunctions(
    #     sentence_types=[{"type": "quantified", "subtype": "name_all"}, {"type": "quantified", "subtype": "name_some"}]
    # )
    # generator.generate_conditionals(
    #     sentence_types=[{"type": "quantified", "subtype": "name_all"}, {"type": "quantified", "subtype": "name_some"}]
    # )
    # generator.generate_biconditionals(only_atomic=True)
    # generator.generate_name_quantified_sentences()
    print(db.sentence_exists("∃x(Mx∧∀y(Ny→Ryx))"))
    print(db.sentence_exists("∀x(Mx→∀y((Ny∧∀z(Mz→Ryz))→Rxy))"))
    print(db.sentence_exists("(Nc∧∀x(Mx→Rcx))"))
    print(db.sentence_exists("∃x(Mx∧Rxc)"))
